const { Router } = require("express");
const router = Router();
const user = require("./users/User");
const modify = require("./users/updatepass");
const deleted = require("./users/deleteuser");
const accountList = require("./count-list-route");
const detailsInformation = require("./details-information-route");
const videoUrlHistory = require("./video-url-history");
const coordsOfDay = require("./coords-of-day");
const videoOfDay = require("./video-of-day");
router.use("/account-list", accountList);
router.use("/detail-information", detailsInformation);
router.use("/coords-of-day", coordsOfDay);
router.use("/video-of-day", videoOfDay);
router.use("/video-url-history", videoUrlHistory);
router.use("/create", user);
router.use("/updatepass", modify);
router.use("/deleteuser", deleted);

module.exports = router;
